# Generated by Django 5.1.7 on 2026-02-11 05:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploadedBy', models.CharField(blank=True, max_length=255)),
                ('submitting_office', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='reports/')),
            ],
        ),
    ]
