# Generated by Django 5.0.14 on 2026-02-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_document_updated_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
