# Generated by Django 5.0.14 on 2026-02-19 07:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_must_change_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, help_text='Position or designation', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='office',
            field=models.CharField(blank=True, help_text='Department', max_length=255),
        ),
    ]
