# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_user_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_number',
        ),
    ]
