# Generated by Django (manual)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='admin_only',
            field=models.BooleanField(default=False, help_text='Only visible to admin users'),
        ),
    ]
