# Generated by Django (manual)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_notification_admin_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user_pr_no',
            field=models.CharField(blank=True, help_text='PR No. (user-entered, for Purchase Request)', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount (for Purchase Request)', max_digits=14, null=True),
        ),
    ]
