# Generated by Django (manual)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_document_user_pr_no_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source_of_fund',
            field=models.CharField(blank=True, help_text='Source of Fund (for Activity Design)', max_length=255),
        ),
    ]
