# Generated by Django (manual)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_document_source_of_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ppmp_no',
            field=models.CharField(blank=True, help_text='PPMP No. (user-entered, for Project Procurement Management Plan/Supplemental PPMP)', max_length=100),
        ),
    ]
