# Generated by Django (manual)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_document_ppmp_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='app_no',
            field=models.CharField(blank=True, help_text='APP No. (for Annual Procurement Plan)', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='app_type',
            field=models.CharField(blank=True, help_text='APP type: Final or Updated (for Annual Procurement Plan)', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='certified_true_copy',
            field=models.BooleanField(default=False, help_text='Certified True Copy? (for Annual Procurement Plan)'),
        ),
        migrations.AddField(
            model_name='document',
            name='certified_signed_by',
            field=models.CharField(blank=True, help_text='Signed by (when Certified True Copy is Yes)', max_length=255),
        ),
    ]
