# Generated by Django (manual)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_document_app_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='market_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget (for Market Scopping)', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='market_period_from',
            field=models.CharField(blank=True, help_text='Period from MM/YY (for Market Scopping)', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='market_period_to',
            field=models.CharField(blank=True, help_text='Period to MM/YY (for Market Scopping)', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='market_expected_delivery',
            field=models.CharField(blank=True, help_text='Expected Delivery MM/YYYY (for Market Scopping)', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='market_service_provider_1',
            field=models.CharField(blank=True, help_text='Service Provider 1 (for Market Scopping)', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='market_service_provider_2',
            field=models.CharField(blank=True, help_text='Service Provider 2 (for Market Scopping)', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='market_service_provider_3',
            field=models.CharField(blank=True, help_text='Service Provider 3 (for Market Scopping)', max_length=255),
        ),
    ]
