# Generated by Django (manual)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_document_market_scoping_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='office_division',
            field=models.CharField(blank=True, help_text='Office/Division (for Requisition and Issue Slip)', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='received_by',
            field=models.CharField(blank=True, help_text='Received By (for Requisition and Issue Slip)', max_length=255),
        ),
    ]
