# Generated by Django 5.0.14 on 2026-02-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_document_requisition_issue_slip_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='prNo',
            field=models.CharField(blank=True, help_text='BAC Folder No. / Transaction number (auto-generated on create, format YYYY-MM-NNN)', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='source_of_fund',
            field=models.CharField(blank=True, help_text='Source of Fund (for Activity Design, PPMP)', max_length=255),
        ),
    ]
