# Generated by Django 5.0.14 on 2026-03-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_document_prno_alter_document_source_of_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='attendance_members',
            field=models.TextField(blank=True, help_text='JSON array of {name, present} (for Attendance Sheet)'),
        ),
        migrations.AddField(
            model_name='document',
            name='date_received',
            field=models.DateField(blank=True, help_text='Date received (for Invitation to COA)', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='prNo',
            field=models.CharField(blank=True, help_text='BAC Folder No. (auto-generated on create, format YYYY-MM-NNN)', max_length=100),
        ),
    ]
