# Generated by Django 5.0.14 on 2026-03-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_add_date_received_attendance_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='resolution_no',
            field=models.CharField(blank=True, help_text='Resolution No. (for BAC Resolution)', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='resolution_option',
            field=models.CharField(blank=True, help_text='Options: LCB, LCRB, SCB, SCRB (for BAC Resolution)', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='venue',
            field=models.CharField(blank=True, help_text='Venue (for BAC Resolution)', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='winning_bidder',
            field=models.CharField(blank=True, help_text='Winning Bidder (for BAC Resolution)', max_length=255),
        ),
    ]
