# Generated by Django 5.0.14 on 2026-03-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_bac_resolution_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='abstract_bidders',
            field=models.TextField(blank=True, help_text='JSON array of {name, amount, remarks} (for Abstract of Quotation), min 3 bidders'),
        ),
        migrations.AddField(
            model_name='document',
            name='aoq_no',
            field=models.CharField(blank=True, help_text='AOQ No. (for Abstract of Quotation)', max_length=100),
        ),
    ]
