# Generated by Django 5.0.14 on 2026-03-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_add_abstract_of_quotation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='notice_award_authorized_rep',
            field=models.CharField(blank=True, help_text='Authorized Representative/Owner (for Notice of Award)', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='notice_award_conforme',
            field=models.CharField(blank=True, help_text='Conforme (for Notice of Award)', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='notice_award_service_provider',
            field=models.CharField(blank=True, help_text='Service Provider (for Notice of Award)', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='table_rating_address',
            field=models.CharField(blank=True, help_text='Address (for Lease of Venue: Table Rating Factor)', max_length=500),
        ),
        migrations.AddField(
            model_name='document',
            name='table_rating_factor_value',
            field=models.CharField(blank=True, help_text='Factor Value (for Lease of Venue: Table Rating Factor)', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='table_rating_service_provider',
            field=models.CharField(blank=True, help_text='Service Provider (for Lease of Venue: Table Rating Factor)', max_length=255),
        ),
    ]
