# Generated by Django 5.0.14 on 2026-03-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_add_table_rating_notice_award_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Contract Amount (for Contract Services/Purchase Order)', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='contract_received_by_coa',
            field=models.BooleanField(default=False, help_text='Received by COA? Yes/No (for Contract Services/Purchase Order)'),
        ),
        migrations.AddField(
            model_name='document',
            name='notarized_date',
            field=models.DateField(blank=True, help_text='Notarized date (for Contract Services/Purchase Order)', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='notarized_place',
            field=models.CharField(blank=True, help_text='Notarized place (for Contract Services/Purchase Order)', max_length=255),
        ),
    ]
