# Generated by Django 5.1.4 on 2026-03-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_add_contract_services_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ntp_service_provider',
            field=models.CharField(blank=True, help_text='Service Provider (for Notice to Proceed)', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='ntp_authorized_rep',
            field=models.CharField(blank=True, help_text='Authorized Representative/Owner (for Notice to Proceed)', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='ntp_received_by',
            field=models.CharField(blank=True, help_text='Received By (for Notice to Proceed)', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='oss_service_provider',
            field=models.CharField(blank=True, help_text='Service Provider (for OSS)', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='oss_authorized_rep',
            field=models.CharField(blank=True, help_text='Authorized Representative/Owner (for OSS)', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='secretary_service_provider',
            field=models.CharField(blank=True, help_text="Service Provider (for Secretary's Certificate)", max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='secretary_owner_rep',
            field=models.CharField(blank=True, help_text="Owner/Authorized Representative (for Secretary's Certificate)", max_length=255),
        ),
    ]
