# Generated by Django 5.0.14 on 2026-03-05 02:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_add_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.document_file_upload_to),
        ),
    ]
