# Generated by Django 5.0.14 on 2026-03-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_document_file_upload_to_by_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('bac_member', 'BAC Member')], default='employee', max_length=10),
        ),
    ]
