# Generated by Django 6.0.2 on 2026-03-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_add_bac_member_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('BAC Chairperson', 'BAC Chairperson'), ('BAC Secretariat', 'BAC Secretariat'), ('BAC Member', 'BAC Member')], help_text='Position or designation', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
