# Generated by Django 5.0.14 on 2026-04-06 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_user_position_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
