# Generated by Django 5.0.14 on 2026-04-16 00:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_delete_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pr_no', models.CharField(help_text='BAC Folder No.', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Title / Purpose', max_length=255)),
                ('user_pr_no', models.CharField(blank=True, help_text='PR No.', max_length=100)),
                ('source_of_fund', models.CharField(blank=True, help_text='Fund Source', max_length=255)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='ABC / Total Amount', max_digits=14, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ongoing', 'Ongoing'), ('under_evaluation', 'Under Evaluation'), ('for_award', 'For Award'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='prNo',
            field=models.CharField(blank=True, help_text='BAC Folder No. (auto-generated on create, format YYYY-MMM-MM)', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='procurement_record',
            field=models.ForeignKey(blank=True, help_text='Link to procurement record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.procurementrecord'),
        ),
    ]
