# Generated by Django 5.0.14 on 2026-04-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_add_procurement_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrecord',
            name='procurement_type',
            field=models.CharField(blank=True, choices=[('lease_of_venue', 'Lease of Venue'), ('small_value', 'Small Value Procurement'), ('public_bidding', 'Public Bidding'), ('negotiated', 'Negotiated Procurement')], help_text='Type of procurement', max_length=50),
        ),
    ]
