# Generated by Django on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_procurementrecord_procurement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('bac_secretariat', 'BAC Secretariat (Admin)'),
                    ('bac_chair', 'BAC Chair'),
                    ('bac_member', 'BAC Member'),
                ],
                default='bac_member',
                max_length=20,
            ),
        ),
    ]