# Generated by Django 5.0.14 on 2026-04-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_update_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether the 1-day reminder email has been sent'),
        ),
    ]
