# Generated by Django 5.0.14 on 2026-04-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_calendarevent_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementrecord',
            name='pr_no',
            field=models.CharField(help_text='BAC Folder No.', max_length=100),
        ),
    ]
