# Generated by Django 5.0.14 on 2026-04-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_procurementrecord_pr_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
