# Generated by Django 5.0.14 on 2026-04-20 01:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_calendarevent_end_time_calendarevent_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrecord',
            name='current_stage',
            field=models.IntegerField(default=1, help_text='Current workflow stage (1-12)'),
        ),
        migrations.AddField(
            model_name='procurementrecord',
            name='end_user_office',
            field=models.CharField(blank=True, help_text='End-User / Office', max_length=255),
        ),
        migrations.AddField(
            model_name='procurementrecord',
            name='mode_of_procurement',
            field=models.CharField(blank=True, help_text='Mode of Procurement', max_length=100),
        ),
        migrations.AddField(
            model_name='procurementrecord',
            name='remarks',
            field=models.TextField(blank=True, help_text='General Remarks'),
        ),
        migrations.AddField(
            model_name='procurementrecord',
            name='rfq_no',
            field=models.CharField(blank=True, help_text='RFQ No.', max_length=100),
        ),
        migrations.AlterField(
            model_name='procurementrecord',
            name='procurement_type',
            field=models.CharField(blank=True, choices=[('lease_of_venue', 'Lease of Venue'), ('small_value', 'Small Value Procurement'), ('public_bidding', 'Public Bidding'), ('negotiated', 'Negotiated Procurement'), ('supplies', 'CSE / Supplies')], help_text='Type of procurement', max_length=50),
        ),
        migrations.AlterField(
            model_name='procurementrecord',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('preparing', 'Preparing Documents'), ('under_review', 'Under Review'), ('for_revision', 'For Revision'), ('approved', 'Approved for Input'), ('for_input', 'For Input'), ('for_posting', 'For Posting'), ('for_float', 'For Float'), ('for_schedule', 'For Schedule'), ('under_evaluation', 'Under Evaluation'), ('for_award', 'For Award'), ('awarded', 'Awarded'), ('for_liquidation', 'For Liquidation'), ('closed', 'Closed')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('Regional Director', 'Regional Director'), ('BAC Chairperson', 'BAC Chairperson'), ('BAC Secretariat', 'BAC Secretariat'), ('BAC Member', 'BAC Member'), ('Supply Officer', 'Supply Officer'), ('Planning Officer', 'Planning Officer'), ('TWG Member', 'TWG Member'), ('End-User', 'End-User')], help_text='Position or designation', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('bac_secretariat', 'BAC Secretariat (Admin)'), ('end_user', 'End-User / Requesting Office'), ('planning_unit', 'Planning Unit'), ('supply_officer', 'Supply Officer'), ('bac_chair', 'BAC Chairperson'), ('bac_member', 'BAC Member'), ('twg', 'Technical Working Group (TWG)'), ('approver', 'Approving Authority')], default='end_user', max_length=20),
        ),
        migrations.CreateModel(
            name='ProcurementStageStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_number', models.IntegerField()),
                ('stage_name', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('procurement_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_statuses', to='api.procurementrecord')),
            ],
            options={
                'ordering': ['stage_number'],
                'unique_together': {('procurement_record', 'stage_number')},
            },
        ),
    ]
