# Generated by Django 5.0.14 on 2026-04-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_procurementrecord_current_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Has an upcoming reminder been sent for this event?'),
        ),
        migrations.AlterField(
            model_name='document',
            name='prNo',
            field=models.CharField(blank=True, help_text='BAC Folder No. (auto-generated on create, format YYYY-MM-NNN)', max_length=100),
        ),
        migrations.AlterField(
            model_name='procurementrecord',
            name='mode_of_procurement',
            field=models.CharField(blank=True, default='', help_text='Mode of Procurement', max_length=100),
        ),
        migrations.AlterField(
            model_name='procurementrecord',
            name='pr_no',
            field=models.CharField(help_text='BAC Folder No.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('BAC Chairperson', 'BAC Chairperson'), ('BAC Secretariat', 'BAC Secretariat'), ('BAC Member', 'BAC Member')], help_text='Position or designation', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
