# Generated by Django 5.0.14 on 2026-04-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_remove_calendarevent_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='quarter',
            field=models.CharField(blank=True, help_text='Quarter (e.g. Q1, Q2)', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.CharField(blank=True, help_text='Year (e.g. 2024)', max_length=4),
        ),
    ]
