# Generated by Django 5.0.14 on 2026-04-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_document_quarter_document_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrecord',
            name='ppmp_no',
            field=models.CharField(blank=True, help_text='Associated PPMP No. for grouping', max_length=100),
        ),
        migrations.AlterField(
            model_name='procurementrecord',
            name='pr_no',
            field=models.CharField(help_text='BAC Folder No.', max_length=100),
        ),
    ]
