# Generated by Django 5.0.14 on 2026-04-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_procurementrecord_quarter_procurementrecord_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pr_items',
            field=models.TextField(blank=True, help_text='JSON array of {unit, description, quantity, unit_cost}'),
        ),
    ]
