# Generated by Django 5.0.14 on 2026-04-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_add_completed_procurement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('BAC Secretariat', 'BAC Secretariat'), ('BAC Member', 'BAC Member')], help_text='Position or designation', max_length=255),
        ),
    ]
