# Generated by Django 5.0.14 on 2026-04-29 01:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_user_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementrecord',
            name='current_stage',
        ),
        migrations.AddField(
            model_name='document',
            name='po_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready_for_po', 'Ready for PO'), ('po_generated', 'PO Generated')], default='pending', help_text='Status of Purchase Order generation for this PR', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('BAC Secretariat', 'BAC Secretariat'), ('BAC Member', 'BAC Member'), ('Supply Officer', 'Supply Officer')], help_text='Position or designation', max_length=255),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_address', models.CharField(blank=True, max_length=500)),
                ('tin', models.CharField(blank=True, max_length=100)),
                ('po_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('mode_of_procurement', models.CharField(blank=True, max_length=100)),
                ('place_of_delivery', models.CharField(blank=True, max_length=255)),
                ('date_of_delivery', models.CharField(blank=True, max_length=255)),
                ('payment_term', models.CharField(blank=True, max_length=100)),
                ('po_items', models.TextField(blank=True, help_text='JSON array of {unit, description, quantity, final_unit_cost, amount}')),
                ('final_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_in_words', models.CharField(blank=True, max_length=500)),
                ('fund_cluster', models.CharField(blank=True, max_length=100)),
                ('funds_available', models.CharField(blank=True, max_length=255)),
                ('ors_burs_no', models.CharField(blank=True, max_length=100)),
                ('date_of_ors_burs', models.DateField(blank=True, null=True)),
                ('ors_burs_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('pr_document', models.ForeignKey(limit_choices_to={'subDoc': 'Purchase Request'}, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='api.document')),
            ],
        ),
        migrations.DeleteModel(
            name='ProcurementStageStatus',
        ),
    ]
