# Generated by Django 5.0.14 on 2026-04-29 05:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_remove_procurementrecord_current_stage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='date',
            new_name='po_date',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='final_total_amount',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='po_items',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='pr_document',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_terms',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pr_no', models.CharField(blank=True, max_length=100)),
                ('purpose', models.TextField(help_text='Purpose of the purchase request')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('po_generated', 'PO Generated'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ppmp', models.ForeignKey(blank=True, help_text='Link to the associated PPMP (Procurement Record)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='api.procurementrecord')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='api.purchaserequest'),
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.purchaserequest')),
            ],
        ),
    ]
