# Generated by Django 5.0.14 on 2026-04-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_rename_date_purchaseorder_po_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('po_generated', 'PO Generated'), ('cancelled', 'Cancelled')], default='approved', max_length=20),
        ),
    ]
