# Generated by Django 5.0.14 on 2026-04-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_purchaserequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrecord',
            name='is_ready',
            field=models.BooleanField(default=False, help_text='True if all mandatory docs (PR, Activity Design, RIS, Market Scoping) are uploaded'),
        ),
        migrations.AlterField(
            model_name='procurementrecord',
            name='user_pr_no',
            field=models.CharField(blank=True, help_text='Official PR No. assigned by BAC', max_length=100),
        ),
    ]
