# Generated by Django 5.0.14 on 2026-04-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_procurementrecord_is_ready_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('bac_secretariat', 'BAC Secretariat'), ('bac_member', 'BAC Member'), ('supply', 'Supply Officer'), ('end_user', 'End User')], default='end_user', max_length=20),
        ),
    ]
