# Generated by Django 5.0.14 on 2026-04-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('po_generated', 'PO Generated'), ('cancelled', 'Cancelled')], default='ongoing', max_length=20),
        ),
    ]
