# Generated by Django 5.0.14 on 2026-04-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_purchaserequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='ors_burs_amount',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
