# Generated by Django 5.0.14 on 2026-04-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_purchaseorder_ors_burs_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestitem',
            name='pr_no',
            field=models.CharField(blank=True, help_text='Denormalized PR No. for reporting', max_length=100, null=True),
        ),
    ]
