# Generated by Django 5.0.14 on 2026-05-03 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_purchaserequestitem_pr_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='If set, only this specific user will see the notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('bac_secretariat', 'BAC Secretariat'), ('bac_member', 'BAC Member'), ('supply', 'Supply Officer'), ('end_user', 'End User')], help_text='If set, only users with this role will see the notification', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='admin_only',
            field=models.BooleanField(default=False, help_text='Deprecated: Use recipient_role="admin" or "bac_secretariat" instead'),
        ),
    ]
