# Generated by Django 5.0.14 on 2026-05-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_cleanup_document_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ppmp_no',
            field=models.CharField(blank=True, help_text='Associated PPMP No.', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='quarter',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
