# Generated by Django 5.0.14 on 2026-05-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_document_ppmp_no_document_quarter_document_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementrecord',
            name='pr_no',
            field=models.CharField(help_text='BAC Folder No.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='procurementrecord',
            name='user_pr_no',
            field=models.CharField(blank=True, help_text='Official PR No. assigned by BAC', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='pr_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
