# Generated by Django 5.0.14 on 2026-05-06 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_alter_procurementrecord_pr_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='prNo',
            field=models.ForeignKey(blank=True, db_column='prNo', help_text='BAC Folder No.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_rel', to='api.procurementrecord', to_field='pr_no'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='api.purchaserequest', to_field='pr_no'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='ppmp',
            field=models.ForeignKey(blank=True, help_text='Link to the associated PPMP (Procurement Record)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='api.procurementrecord', to_field='pr_no'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='pr_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
